<!DOCTYPE html>

<html lang="fr">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="blog Jeans Forteroch">

    <title>Jean Forteroch</title>

    <link rel="stylesheet" href="http://localhost/projet4/public/style/style.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet'
          type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
          rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
<?php require_once 'header.phtml' ?>
<hr>

<div class="container article">
    <div class="card border-info ">
        <div class="card-body ">
            <h1 class="card-title text-center"><?= $article->getTitle(); ?></h1>
            <p class=" content"><?= $article->getContent(); ?></p>
        </div>
    </div>
    <hr>
    <div class="card text-white bg-primary">
        <h3 class="text-center">Les commentaires</h3>
        <?php foreach ($comments as $comment): ?>

            <?= htmlspecialchars($comment->getAuthor()); ?> : <?= htmlspecialchars($comment->getComment()); ?>

            <?php if ($comment->getSignale() == 1): ?>
                <i class="fa fa-window-close " aria-hidden="true"></i>
            <?php endif; ?>
            <form class="d-inline-block" action="" method="post">
                <input class="btn btn-danger" type="submit" value="signale"/>
                <input class="btn btn-danger" type="hidden" name="signale" value="<?= $comment->getId(); ?>">
            </form>

        <?php endforeach; ?>

    </div>

    <div class="form-group commentaire">
        <form action="" method='post'>
            <label class="text-primary" for="pseudo">Pseudo :</label>
            <input type="text" name="author" required><br>
            <label class="text-primary" for="commentaire">Commentaire :</label>
            <textarea class="form-control" name="commentaire" required></textarea>
            <br><input class="btn btn-primary" type="submit">
        </form>
    </div>


</div>
<?php require_once "footer.phtml" ?>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>


</body>

</html>