<!DOCTYPE html>

<html lang="fr">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="blog Jeans Forteroch">

    <title>Jean Forteroch</title>

    <link rel="stylesheet" href="http://localhost/projet4/public/style/style.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet'
          type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
          rel='stylesheet' type='text/css'>

</head>

<body>

<?php require_once 'adminHeader.phtml' ;?>
<div class="dashboard">
    <?php
    if (isset($commentsignaler) && !empty($commentsignaler)) {
        include "commentSignale.phtml";
    }
    ?>
    <div id="articles">
        <h3 class="text-center">Gestion d'articles</h3>
        <hr>
        <form method="post">
            <div class="add-post">
                <h3>titre</h3>
                <input type="text" name="title">
                <h3>contenu</h3>
                <textarea name="content" id="" cols="30" rows="10"></textarea>
                <input class="btn btn-default" type="submit" name="add" value="ajouter">
            </div>
            <hr>
            <div class="delete-post">
                <h4 class="text-center">Edité ou supprimer un article</h4>
                <?php foreach ($articles as $article): ?>

                    <ul>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <h3>Titre : <?= $article->getTitle(); ?></h3>
                            <a class="badge badge-success "
                               href="index.php?action=connexion&edit=action&article=<?= $article->getId(); ?>">editer</a>
                            <input type="checkbox" name="delete_article[]" value= <?= $article->getId(); ?>>
                        </li>
                    </ul>
                <?php endforeach; ?>
                <input class="btn btn-danger supprimer" type="submit" name="supprimer" value="supprimer">
            </div>

        </form>

    </div>


</div>


<script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>
<script>tinymce.init({selector: 'textarea'});</script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>


</body>

</html>