<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <p class="navbar-brand">Jeans Forteroch</p>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link " href="index.php">Accueil<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="index.php?action=connexion">Admin</a>
            </li>
        </ul>
    </div>
</nav>

<header class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1 class="text-center">Billet simple pour l'Alaska</h1>
                    <hr class="small">
                    <p class="text-center">Bienvenue sur le blog de Jeans Forteroch</p>
                </div>
            </div>
        </div>
    </div>
</header>

